import { useEffect, useState } from 'react'
import { getRiskSummary } from './backendClient.js'
import { useInteractionCheck } from './useInteractionCheck.js'

function SparkleIcon() {
  return (
    <svg viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">
      <path
        d="M12 3l1.8 5.2L19 10l-5.2 1.8L12 17l-1.8-5.2L5 10l5.2-1.8L12 3z"
        fill="currentColor"
      />
    </svg>
  )
}

// A one-paragraph, plain-language "here's your overall picture" summary,
// generated by Gemini from whatever InteractionResults.jsx would show as
// a list anyway (see backend/app/gemini_client.py's summarize_risk and
// POST /api/risk-summary). Deliberately reuses useInteractionCheck rather
// than taking interactions as a prop — same self-contained-component
// philosophy as InteractionResults/BodyMap, and the per-pair explanation
// cache in gemini_client.py means this doesn't add extra Gemini load
// beyond what the interaction list already causes.
function RiskSummaryCard({ medications }) {
  const { interactions, loading: loadingInteractions, error: interactionsError } =
    useInteractionCheck(medications)
  const [summary, setSummary] = useState(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')

  useEffect(() => {
    if (loadingInteractions || interactionsError) return
    let cancelled = false
    setLoading(true)
    setError('')

    getRiskSummary({ medications, interactions })
      .then((text) => {
        if (!cancelled) setSummary(text)
      })
      .catch((err) => {
        console.warn('Risk summary unavailable:', err.message)
        if (!cancelled) setError("Couldn't generate an AI summary right now — see the full list below.")
      })
      .finally(() => {
        if (!cancelled) setLoading(false)
      })

    return () => {
      cancelled = true
    }
    // Re-run only when the actual interaction set changes, not on every
    // parent re-render.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [loadingInteractions, interactionsError, JSON.stringify(interactions.map((i) => [i.drugs, i.severity]))])

  if (loadingInteractions || loading) {
    return (
      <div className="risk-summary-card">
        <span className="risk-summary-icon">
          <SparkleIcon />
        </span>
        <p className="med-list-empty">Reading your medication list…</p>
      </div>
    )
  }

  // Previously rendered nothing at all here (the interaction list elsewhere
  // on the page already surfaced the real error/list) — but that left a
  // blank, oddly-empty-looking card behind whenever this ran standalone
  // (no GEMINI_API_KEY configured, or a transient failure), which reads as
  // broken rather than "nothing to show." A plain-language fallback is a
  // better default wherever this card is used.
  if (interactionsError || error || !summary) {
    return (
      <div className="risk-summary-card">
        <span className="risk-summary-icon">
          <SparkleIcon />
        </span>
        <p className="risk-summary-text">
          {interactionsError || error || "An AI summary isn't available right now — see the details below."}
        </p>
      </div>
    )
  }

  return (
    <div className="risk-summary-card">
      <span className="risk-summary-icon">
        <SparkleIcon />
      </span>
      <p className="risk-summary-text">{summary}</p>
    </div>
  )
}

export default RiskSummaryCard
